name: json_serializable_collector
description: This bad code will help you improve your life. I wrote as best as I could. If you know how to write this utility better - write. Criticism is unacceptable. PRs are welcome.
version: 1.0.0

# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  build: ^2.2.1
  json_annotation: ^4.4.0
  meta: ^1.7.0
  path: ^1.8.0
  source_gen: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.0
